name: deploy-main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host my-server
            HostName $EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh my-server '
            set -e

            cd ~/Backend

            # 안전한 풀
            git fetch origin main
            git checkout main
            git pull --ff-only origin main

            # PM2 보장 설치(최초 대비)
            command -v pm2 >/dev/null 2>&1 || npm i -g pm2

            # 의존성 설치
            npm ci

            # Prisma
            npx prisma generate
            npx prisma migrate deploy

            # dev 의존성 제거(선택)
            npm prune --omit=dev || true

            # PM2: 있으면 reload, 없으면 start
            if pm2 list | grep -q "backend"; then
              pm2 reload ecosystem.config.cjs --only backend --update-env
            else
              pm2 start ecosystem.config.cjs --only backend --env production
            fi

            pm2 save
          '
